### ISSUE TITLE
dúvida

### ISSUE THREAD

**Issue by rosset** [FabianoTSS/intelbras-firmwares#1]
olá Fabiano, tudo bem?
estava lendo seu update na thread https://forum.openwrt.org/t/adding-device-support-tp-link-wr941hp/46548/91
1) Instalei a primeira imagem e está tudo OK operacional, fiz a instalação via web mesmo, meu firmware anterior era o TLWR941HPv2_br-up-ver2-0-1-P1[20190522

First, install this image here: [openwrt-ath79-generic-tplink_tl-wr941hp-v2-squashfs-factory.bin](https://github.com/FabianoTSS/custom-firmwares/raw/tplink/tl-wr941hp-v2/firmware/openwrt/openwrt-ath79-generic-tplink_tl-wr941hp-v2-squashfs-factory.bin)

Para que servem as outras duas imagens? É o primeiro router que eu instalo o openwrt.
openwrt-ath79-generic-tplink_tl-wr941hp-v2-initramfs-kernel.bin
openwrt-ath79-generic-tplink_tl-wr941hp-v2-squashfs-sysupgrade.bin

![image](https://github.com/FabianoTSS/custom-firmwares/assets/45233/a6ba2dfe-e258-481c-991f-54c1dcaac580)

**Comment by fbinerd** [comment]
A imagem factory serve para instalar o openwrt pela primeira vez a partir do firmware da TP-Link, a imagem sysupgrade serve para atualizar a versão do firmware ex: a imagem está na versão 23.05, se você quiser ir para a versão 23.05.rc2 ou mais recente,  você precisa baixar uma imagem nova sysupgrade na versão desejada. A imagem initramfs em combinação com um cabo TTL, serve para iniciar o openwrt no roteador sem fazer flash para fins de teste sem correr o risco de danificar o roteador com um firmware ruim. Atualmente, das imagens fornecidas, você só vai precisar da imagem factory, pois não há uma nova versão compilada para esse roteador. Eu apenas coloquei lá as imagens para o caso de alguém querer testar ou analisar a estrutura das mesmas.

**Comment by rosset** [comment]
apenas para confirmar, esta tudo estavel por aqui funcionando ja por 3 semanas, obrigado.

**Comment by rosset** [comment]
closing
